### ISSUE TITLE
Create telegram bot assistant for community

### ISSUE THREAD

**Issue by orzklv** [mad-maids/telegram#1]

**Comment by akumarujon** [comment]
Rewriting in Deno?

**Comment by orzklv** [comment]
> Rewriting in Deno?

I support whatever new & is supported by Vercel =)

**Comment by akumarujon** [comment]
I didn't know if Vercel supports Deno or not. Some researches gave me the "yes".

So we can use Deno too.

https://vercel.com/docs/functions/serverless-functions/runtimes

**Comment by akumarujon** [comment]
But I don't know If that's a good choice while we have recommended option Deno Deploy.

**Comment by orzklv** [comment]
> I didn't know if Vercel supports Deno or not. Some researches gave me the "yes".
> 
> So we can use Deno too.
> 
> [vercel.com/docs/functions/serverless-functions/runtimes](https://vercel.com/docs/functions/serverless-functions/runtimes)

[I know )](https://github.com/vercel-community/deno/commit/6b02e1120567f52202e3f31f624f7c243e7522f1), but not all API is supported yet...

**Comment by akumarujon** [comment]
> > I didn't know if Vercel supports Deno or not. Some researches gave me the "yes".
> > So we can use Deno too.
> > [vercel.com/docs/functions/serverless-functions/runtimes](https://vercel.com/docs/functions/serverless-functions/runtimes)
> 
> [I know )](https://github.com/vercel-community/deno/commit/6b02e1120567f52202e3f31f624f7c243e7522f1), but not all API is supported yet...

Do we need all of them? Can we use Grammy with Vercel's Deno?

**Comment by orzklv** [comment]
> > > I didn't know if Vercel supports Deno or not. Some researches gave me the "yes".
> > > So we can use Deno too.
> > > [vercel.com/docs/functions/serverless-functions/runtimes](https://vercel.com/docs/functions/serverless-functions/runtimes)
> > 
> > 
> > [I know )](https://github.com/vercel-community/deno/commit/6b02e1120567f52202e3f31f624f7c243e7522f1), but not all API is supported yet...
> 
> Do we need all of them? Can we use Grammy with Vercel's Deno?

By the time when I tested it, a few node shims were unstable that led to 500 response. I'm still not sure whether does it work or not. If you have a tested version or experience on this, I'm happy to accept PR!
